apiVersion: v1
kind: PersistentVolume
metadata:
  name: dv-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default